GET http://localhost:3000/user

###

POST http://localhost:3000/user/signup
Content-Type: application/json

{
    "userName": "Meitargo",
    "name": "Meitar",
    "lastName": "Goldberger",
    "city": "Modi'in",
    "email": "maitarg123@gmail.com",
    "password": "password"
}

###

POST http://localhost:3000/user/login
Content-Type: application/json

{
    "userName": "Meitargo",
    "password": "password"
}